Repository ros/class_loader, pull requests merged in 2018-02, with the labels that each got.

#82 Exceptions fixups
  include/class_loader/class_loader_core.h
  include/class_loader/class_loader_exceptions.h
  src/class_loader_core.cpp
Labels: in review

#83 comply with package format2 xsd
  package.xml
Labels: in progress

#85 comply with package format2 xsd (#83)
  package.xml
Labels: in review

#81 deprecate .h headers in favor of .hpp headers
  CMakeLists.txt
  include/class_loader/class_loader.h
  include/class_loader/class_loader.hpp
  include/class_loader/class_loader_core.h
  include/class_loader/class_loader_core.hpp
  include/class_loader/class_loader_exceptions.h
  include/class_loader/class_loader_register_macro.h
  include/class_loader/exceptions.hpp
  include/class_loader/meta_object.h
  include/class_loader/meta_object.hpp
  include/class_loader/multi_library_class_loader.h
  include/class_loader/multi_library_class_loader.hpp
  include/class_loader/register_macro.hpp
  scripts/class_loader_headers_update.py
  src/class_loader.cpp
  src/class_loader_core.cpp
  src/meta_object.cpp
  src/multi_library_class_loader.cpp
  test/base.hpp
  test/plugins1.cpp
  test/plugins2.cpp
  test/unique_ptr_test.cpp
  test/utest.cpp
Labels: in progress

#86 use std::string references for exceptions
  include/class_loader/exceptions.hpp
Labels: in progress

#87 Stop checking for c++11 support
  include/class_loader/class_loader.hpp
  include/class_loader/multi_library_class_loader.hpp
  test/CMakeLists.txt
Labels: in review

#88 fix non-defined variable
  CMakeLists.txt
Labels: needs_port_other_distros
